
// This file has been generated by the GUI designer. Do not modify.
namespace Project.Framework.ViewMain
{
	public partial class WindowMain
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Project.Framework.ViewMain.WindowMain
			this.Name = "Project.Framework.ViewMain.WindowMain";
			this.Title = global::Mono.Unix.Catalog.GetString ("WindowMain");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
